### ISSUE TITLE
Creación de la entidad Inventario

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.lh.2023.spring#10]
Se requiere la creación de los siguientes elementos que representen a la entidad `Inventario`

- Entity
- Repository
- Service
- Service (JPA)
- Controller (con los métodos mostrarTodos, mostrarPorId, crear, modificar y eliminar)

Los atributos sugeridos para la entidad son:

- id (Integer)
- numeroSerie (String)
- disponible (boolean)
- observaciones (String)
- catalogoId (Integer)

**Comment by EliasVal303** [comment]
ya termine la entidad inventario
