### ISSUE TITLE
Mejoras en la entidad: Catálogo

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.lh.2023.spring#30]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la eliminación de un nuevo elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, debes documentar con comentarios el método de la petición`GET` (obtener sólo un elemento por Id)*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 13 de Octubre y la entrega final el 20 de Octubre**

**Comment by Lore9022** [comment]
Adjunto pruebas de Postman

![post1](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/ebc3afa9-2560-48fa-a8ba-84dcb0d26a71)
![post2](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/3c61b9e8-e8a1-4c7b-9019-085d5fa60be0)
![put1](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/5a6c39f5-16c1-44cc-9aea-275b1f6c2838)
![put2](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/dd1c1c4f-dd5a-4576-a1bc-9fdca0b49040)
![delete1](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/8593c9fa-38a8-4027-b50e-ed64cbb3495e)
![delete2](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/789bbd43-eda3-4da3-8b69-8522df99f8ce)
![get1](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/d87c10e4-7db1-4dc9-b28d-361ea90c214c)
![get2](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/72b56fd9-0015-4684-95e1-527afbbb09e2)
![get3](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/85725340/e291239e-64bb-4df1-b9e3-f43158b4059c)
