### ISSUE TITLE
Mejoras en la entidad: Pago

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.lh.2023.spring#32]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la eliminación de un nuevo elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método asociado a la petición `PUT`*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 13 de Octubre y la entrega final el 20 de Octubre**

**Comment by calabretto** [comment]
Get All
![Captura de pantalla 2023-10-31 232839](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/ea9ec080-affe-4fd2-b4b1-efbf3ed8ee59)
Get By Id
![Captura de pantalla 2023-10-31 232934](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/b406c9a4-bac2-4fcb-bfab-d2c7465e5efe)
Post
![Captura de pantalla 2023-10-31 233453](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/64156904-8606-402e-a9f5-180e7ffd8941)
Put
![Captura de pantalla 2023-10-31 233607](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/07ea5486-785b-4c2f-aa28-7fed37ac2869)
Put (Error, id inexistente)
![Captura de pantalla 2023-10-31 233619](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/5f19ec65-7fe2-4611-9b17-117463a41300)
Delete by Id ![Captura de pantalla 2023-10-31 233644](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/3802eedd-4749-4b17-a288-e3fe4e076819)
Delete by Id Incorrecto (Id inecxistente)
![Captura de pantalla 2023-10-31 233654](https://github.com/ahumadamob/imb.pr3.lh.2023.spring/assets/102331029/3ae1287f-d106-43ea-b69b-b6154416fa37)
